### PR TITLE
Review and refactor namespace and imports

### PR DESCRIPTION
**Pull request by samlamont**
Adds classes relevant to the user to `src/teehr/__init__.py` 

With this pattern the user could do things like:

```python
import teehr

ev = teehr.Evaluation()

attr1 = teehr.Attribute(
    name="test",
    type="categorical",
    description="some test"
)

boot1 = teehr.Bootstrappers.CircularBlock(seed=42, reps=500)
metric1 = teehr.Metrics.AnnualPeakRelativeBias(bootstrap=boot1)
```

### CODE REVIEW

**Comment by samlamont** [comment]
@mgdenno Let me know if you have any thoughts, open to suggestions

**Comment by mgdenno** [comment]
@samlamont I think making the common imports available via `teehr` is a good idea.  I am a little concerned that `teehr.Metrics.AnnualPeakRelativeBias()`, etc. starts to get pretty verbose as a standard pattern.

The user can really do what they want, so something like the following would work, right?
```
import teehr.Metrics as m # or
from teehr import Metrics as m

metric1 = m.AnnualPeakRelativeBias()
```

But we should be consistent in how we present it our examples, so good to sort out what our standard is here.

**Comment by samlamont** [comment]
@mgdenno OK sounds good, I agree about using a less verbose pattern as well.  We could do  the same with the bootstrappers throughout the docs:
```python
import teehr.Bootstrappers as b

boot1 = b.CircularBlock(seed=42, reps=500)
```
and the remaining classes we could just access directly from `teehr`? I think the `Metrics` and `Bootstrappers` classes are the only ones that are "containers" for other classes

Not  sure if I have strong opinions as long as we're consistent in the docs and we let the user know that they can import any way they want.  Maybe you can choose a pattern that seems to work during #280 and we'll go with that?

**Comment by samlamont** [comment]
@mgdenno Are you OK with merging this?  This just adds the class imports to the `__init__.py` file, I was thinking we could change the actual import patterns in the other issues related to doc updates.

**Comment by mgdenno** [comment]
@samlamont yeah, go ahead.

**Pull request merged**
