### PR TITLE
55 add flag to control behavior when files are missing

### PR DESCRIPTION
**Pull request by samlamont**
- Added the boolean flag `crash_on_missing_file` to point and grid loading scripts for NWM2.2 data
- `True` will fail if a missing file is encountered, `False` ignores and continues
- Checks during scanning of GCS directory and creation of zarr jsons as well as during the read of the zarr dataset in case of erroneous json files
- Re-names `zone` to `location_id` in grid processing to address issue #63

### CODE REVIEW

**Comment by samlamont** [comment]
@mgdenno , sure I agree `ignore_missing_files` is more clear.   And yes I can add the check for existing files.  Do you want to explore storing the jsons in a bucket to keep a running collection of files or just check locally as specified by `json_dir`?

**Comment by mgdenno** [comment]
@samlamont I think just checking where we store the jsons is sufficient for now and will speed up the process with minimal effort.

**Comment by samlamont** [comment]
@mgdenno sounds good I'll work on that

**Comment by samlamont** [comment]
@mgdenno, made the suggested changes if you want to take another look

**Review by mgdenno — APPROVED** [review]

**Pull request merged**
